# Generated by Django 4.2.9 on 2024-01-31 14:18

from django.db import migrations


def migrate_phone_numbers(apps, schema_editor):
    CustomUser = apps.get_model('customuser', 'CustomUser')
    for customuser in CustomUser.objects.all():
        # Access the phone number value as a string in E.164 format
        phone_number = str(customuser.phone_number.as_e164)
        # Remove the leading '+' sign from each phone number
        if phone_number.startswith('+'):
            phone_number = phone_number[1:]
            # Update the phone number in the database
            customuser.phone_number = phone_number
            customuser.save()

class Migration(migrations.Migration):
    dependencies = [
        ('customuser', '0003_customuser_address'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]