# Generated by Django 4.2.9 on 2024-01-31 13:55

from django.db import migrations


def migrate_phone_numbers(apps, schema_editor):
    Booking = apps.get_model('restaurantpage', 'Booking')
    for booking in Booking.objects.all():
        # Remove the leading '+' sign from each phone number
        if booking.phone_number.startswith('+'):
            booking.phone_number = booking.phone_number[1:]
            booking.save()

class Migration(migrations.Migration):
    dependencies = [
        ('restaurantpage', '0003_alter_booking_phone_number'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]