# Generated by Django 4.2.9 on 2024-01-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantpage', '0003_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
