# Generated by Django 4.2.9 on 2024-01-31 14:12

from django.db import migrations


def migrate_phone_numbers(apps, schema_editor):
    Restaurant = apps.get_model('restaurantpage', 'Restaurant')
    for restaurant in Restaurant.objects.all():
        # Access the phone number value as a string in E.164 format
        phone_number = str(restaurant.phone_number.as_e164)
        # Remove the leading '+' sign from each phone number
        if phone_number.startswith('+'):
            phone_number = phone_number[1:]
            # Update the phone number in the database
            restaurant.phone_number = phone_number
            restaurant.save()

class Migration(migrations.Migration):
    dependencies = [
        ('restaurantpage', '0004_auto_20240131_1355'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]