# Generated by Django 4.2.9 on 2024-01-31 14:31

from django.db import migrations


from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber

def migrate_phone_numbers(apps, schema_editor):
    Restaurant = apps.get_model('restaurantpage', 'Restaurant')
    default_phone_number = PhoneNumber.from_string('+1234567890')  # Set your desired default phone number here
    for restaurant in Restaurant.objects.all():
        if restaurant.phone_number is None:  # Check if phone_number is None
            restaurant.phone_number = default_phone_number
            restaurant.save()

class Migration(migrations.Migration):
    dependencies = [
        ('restaurantpage', '0005_auto_20240131_1412'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]