# Generated by Django 4.2.9 on 2024-01-31 14:33

from django.db import migrations
from phonenumber_field.phonenumber import PhoneNumber

def migrate_phone_numbers(apps, schema_editor):
    Booking = apps.get_model('restaurantpage', 'Booking')
    default_phone_number = PhoneNumber.from_string('+1234567890')  # Set your desired default phone number here
    for booking in Booking.objects.all():
        if booking.phone_number is None or not booking.phone_number:
            booking.phone_number = default_phone_number
            booking.save()

class Migration(migrations.Migration):
    dependencies = [
        ('restaurantpage', '0006_auto_20240131_1431'),
    ]

    operations = [
        migrations.RunPython(migrate_phone_numbers),
    ]