# Generated by Django 4.2.9 on 2024-02-01 15:58

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantpage', '0007_auto_20240131_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, null=True, populate_from=('restaurant__name', 'booked_on'), unique=True),
        ),
    ]
