# Generated by Django 4.2.9 on 2024-02-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantpage', '0008_booking_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True),
        ),
    ]
